//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideImage
    {
        public string slideID { get; set; }
        public string slideTitle { get; set; }
        public byte[] slideImage1 { get; set; }
    }
}
